protocol:
  id: "3"  # The integer unique identifier used for data storage
  name: "sinusoidal_force_disturbance"  # The identifier of the protocol to be used in the current experiment
  notes: ""  # Some relevant notes regarding the experiment setup
  repetitions: 3  # The number of repetitions of the experiment
  parameters:
    id: "0000"  # The integer unique identifier used for data storage
    force_amplitude: 0.0  # The pendulum sinusoidal force amplitude [N]
    frequency: 0.0  # The pendulum oscillation frequency [Hz]
    cycles_number: 10  # The number of sinusoidal periods