protocol:
  id: "4"  # The integer unique identifier used for data storage
  name: "quasi_static_displacement_disturbance"  # The identifier of the protocol to be used in the current experiment
  notes: ""  # Some relevant notes regarding the experiment setup
  repetitions: 3  # The number of repetitions of the experiment
  parameters:
    id: "0"  # The integer unique identifier used for data storage
    displacement_ramp_slope: 0.0  # The pendulum displacement ramp slope [deg/s]