protocol:
  id: "2"  # The integer unique identifier used for data storage
  name: "sinusoidal_displacement_disturbance"  # The identifier of the protocol to be used in the current experiment
  notes: ""  # Some relevant notes regarding the experiment setup
  repetitions: 3  # The number of repetitions of the experiment
  parameters:
    id: "000"  # The integer unique identifier used for data storage
    displacement_amplitude: 0.0  # The pendulum sinusoidal displacement amplitude [deg]
    frequency: 0.0  # The pendulum oscillation frequency [Hz]
    cycles_number: 10  # The number of sinusoidal periods