subject:
  name: ""  # The identifier (e.g. name) of the subject performing the experiment
  mass: 0.0  # The subject mass [kg]
  height: 0.0  # The subject height [m]
  com_height: 0.0  # The subject Center of Mass height [m]
  base_depth: 0.0  # The subject base depth [m]
  base_width: 0.0  # The subject base width [m]
  orientation: 0.0  # The subject orientation w.r.t. the pendulum [deg]